version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev

  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./identity-service:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev

  grade-service:
    build:
      context: ./grade-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./grade-service:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile.dev
    volumes: 
      - ./notification-service:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev
    
